### ISSUE TITLE
Actividad 3

### ISSUE THREAD

**Issue by blnzln** [ING559/Syllabus-2020-2#4]
Hola profe, me iba a poner a hacer la actividad 3 (que es para el viernes) pero no la encuentro por ningún lado.
Gracias
@alanezz

**Comment by oberettag** [comment]
está en la carpeta jupyter

**Comment by alanezz** [comment]
Toda la razón, me pifié. La muevo ahora a la carpeta de actividades.

Gracias!

**Comment by blnzln** [comment]
Gracias
