### ISSUE TITLE
Value en Predict

### ISSUE THREAD

**Issue by oberettag** [ING559/Syllabus-2020-2#6]
Hola profe, 
tenemos una duda con respecto a la función predict, tenemos que suponer que esta función ya conoce los beta o dentro de value deben estar los beta? 
En la misma línea, queríamos saber qué hay dentro de value? es una lista o una matriz o qué es?
Saludos!

**Comment by alanezz** [comment]
Hola!

Se supone que los valores de beta están guardados en la clase que deberías llamar como `self.beta`. Ahora bien, si no estás usando clases, puedes pasar los beta como parámetro de la función. En el value pueden asumir lo que quieran. Yo lo pensé como que es una "observación" en formato de una lista con los valores para cada feature.

Saludos.
