### ISSUE TITLE
Error Gráficos parte 3 Actividad 3

### ISSUE THREAD

**Issue by karteaga00** [ING559/Syllabus-2020-2#7]
hola profesor,
estoy haciendo la parte 3 de la actividad y en el proceso de graficar me tira errores con LogisticRegression, diciendo que predict_proba y coef_ no son atributos del mismo
estoy utilizando collab, intenté hacerlo por jupyter y me continuó lanzando el mismo error
¿cómo puedo solucionarlo?
dejo los errores:
AttributeError: 'LogisticRegression' object has no attribute 'predict_proba'
AttributeError: 'LogisticRegression' object has no attribute 'coef_'

Saludos!

**Comment by alanezz** [comment]
Hola!

Recuerda que aquí estás definiendo tu propia clase, así que la clase LogisticRegression es la que implementaste tú. Para obtener la probabilidad tienes que usar tu método predict y los coeficientes son los beta de tu clase. Si ves el video de la ayudantía vas a cómo lo hice yo.

Saludos!
