### ISSUE TITLE
Duda log_reg.beta

### ISSUE THREAD

**Issue by ItaloJavier** [ING559/Syllabus-2020-2#8]
Hola profe, tenemos una duda en la parte de partial de la función train (y luego la de predict).
Lo que hizo en ayudantía fue usar log_reg fuera de la función, para entrenar el modelo y guardar los betas; ¿por qué lo colocó dentro de la función train (log_reg.beta)? No debería ser self.beta?

partial = partial + ((float(sigmoid(**log_reg.beta**.T.dot(X[i,:].reshape(3,1))))) - float(y[i]))*float(X[i, j])

Se probó el código con ambos y funciona; pero nos parece que debe ser con self.beta porque así no hacemos que la función depende de algo que está afuera.

Gracias!

**Comment by alanezz** [comment]
Hola, toda la razón, es un typo mío. Tiene que ser `self.beta`.

Saludos!
