### ISSUE TITLE
Duda Parte 2

### ISSUE THREAD

**Issue by Alvaro-Weiss** [ING559/Syllabus-2020-2#9]
Una consulta: En la parte 2 solo hay que entrenar el modelo y nada más. Estamos un tanto enredados porque el enunciado dice que debemos hacer un clasificador, sin embargo el algoritmo de Regresión Logística es un algoritmo de clasificación, entonces nos enredamos respecto de que hay que responder.

**Comment by alanezz** [comment]
Claro, la idea es hacer el **clasificador de Iris Virginica**. Tu clase por si sola no hace nada, pero después de entrenarla con los datos correspondientes va a poder clasificar flores. Entonces en la pregunta 2 la idea es que hagas fit del modelo que programaste con el dataset que usamos en clases y que te asegures que todo funciona.

Saludos.
